# Generated by Django 3.2.5 on 2021-08-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0003_auto_20210819_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotion',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
