# Generated by Django 3.2.5 on 2021-08-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangchu', '0004_alter_product_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
